# Generated by Django 4.2.20 on 2025-04-08 18:17

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("projet_postgresql", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="vector_search",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
    ]
