# Generated by Django 4.2.20 on 2025-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projet_postgresql", "0002_alter_produit_vector_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.FloatField(),
        ),
    ]
