# Generated by Django 4.2.20 on 2025-04-09 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet_postgresql", "0003_alter_produit_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="localisation",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
